### ISSUE TITLE
Watcher option is not configured on the config.file

### ISSUE THREAD

**Issue by aperezg** [friendsofgo/killgrave#75]
## Context

All the options that the command line tool can do, the config file should be replicate also, but the `watcher` options is not parsed when the config is load.

## Proposed implementation
Add the watcher option on the parser for config file.

**Comment by Amirhossein2000** [comment]
Hi
I want to work on this.

```yml
imposters_path: "imposters"
port: 3000
host: "localhost"
proxy:
  url: https://example.com
  mode: missing
cors:
  methods: ["GET"]
  headers: ["Content-Type"]
  exposed_headers: ["Cache-Control"]
  origins: ["*"]
  allow_credentials: true
watcher: true
```
the watcher option place is good now? if it's not tell me where is the best place for it and please assign this issue to me.
