### ISSUE TITLE
Problems using the Docker way

### ISSUE THREAD

**Issue by hitokiri** [friendsofgo/killgrave#99]
I have the next problem; you say to use this line to can run the Docker image
docker run -it --rm -p 3000:3000 -v $PWD/:/home -w /home friendsofgo/killgrave -h 0.0.0.0

but when y run this with this tree configuration

> mymock/
>  --     imposters/
>     -- --      config.yml
>     -- --     swapi_people.imp.json
>     -- --     swapi_planets.imp.json
> 

the image logs return the next message
![image](https://user-images.githubusercontent.com/247528/119844867-057fdd80-bec6-11eb-9206-56be12c1dd7e.png)

**Comment by ni507** [comment]
Had the same issue. For me `docker run -it --rm -p 3000:3000 -v $PWD/:/home -w /home friendsofgo/killgrave -config config.yml` without `-h 0.0.0.0` but with the `config.yml` was working.
```
#config.yml

imposters_path: "imposters"
port: 3000
host: "0.0.0.0"
watcher: false
cors:
  methods: ["GET"]
  headers: ["Content-Type"]
  exposed_headers: ["Cache-Control"]
  origins: ["*"]
  allow_credentials: true
```
